line.bot:
  channel-token: "RvAYPFzyDbs+6xsIdzQJN3xZDm2O3rNUFVXOgqUqwlJYn3ZVjCjrHhny509T/O5Gm8l9QJR+fhthYS58eKzDhnIhQIdHOnblfSHSOlofImI9S3DaanonIZ8bhDEnyR+97DeL1/q1HsNKP3BtyucmPQdB04t89/1O/w1cDnyilFU="
  channel-secret: '334c522f9936567ce2b22f18016be253'
  handler.path: /callback
  
#logging.level:
#   com.linecorp.bot.client.wire: INFO