line.bot:
  channel-token: 'wb8j7ThVe3/EkF5JifrstV7J+7RXMZkDMGVeHjygjGIDvCs9s1iwqkFhslzGRRjqSh1KFwNvBM2ghwdGVK0VG0RsD3aBYzMaFlE7C5a7a/FqGbHOiHgVNGb5Y/Ti6z+MoIXFSVxEia9dDdJ4/Pj+CwdB04t89/1O/w1cDnyilFU='
  channel-secret: 'b98ec764f6b609527ae34446d4e6a1cf'
  handler.path: /callback

#logging.level:
#   com.linecorp.bot.client.wire: INFO