line.bot:
  channel-token: '5YloGg5p3vjDNlkh2kNYiXhlLO5pACLeDYAzW+kK3OFtcAph/jL8cqIDyhoiJ2LzXFDSAIiBHHpPgoSsf6MXC4S/wGcVq7TvxPVJynP7U9fyIvVJNfTCBVNuy3vDoVorD7LHkTD3RWVv3v6JUxkiTgdB04t89/1O/w1cDnyilFU='
  channel-secret: '47288c083bc2bf84e849f1a162e64fa1'
  handler.path: /callback
  
#logging.level:
#   com.linecorp.bot.client.wire: INFO