line.bot:
  channel-token: 'biC/KTeQmbWNSS3MhInebkmloIkw636mQ8KfW66uavtn/U3wrS/u1pZP3NSvCJ8sSh1KFwNvBM2ghwdGVK0VG0RsD3aBYzMaFlE7C5a7a/HZL/+5IelqndLVSQy4phKu3dH21hlwycuI9sq8f9uUEwdB04t89/1O/w1cDnyilFU='
  channel-secret: '1efd9ec85bf96834030d0fd63f0e1424'
  handler.path: /callback

#logging.level:
#   com.linecorp.bot.client.wire: INFO

spring.redis:
  database: 1
  host: 35.229.213.2
  port: 6379
  password: km4Eq4hj
  timeout: 5000
  jedis:
    pool:
      max-active: 20
      max-idle: 20
      min-idle: 10

sheet-id:
  product: '1qenyxoIhzbHK-09nVxnVpDBlp3LepvQ7ALmXZKzPV7s'
