line.bot:
  channel-token: 'm5Y7rKDvJctPuHLcRHgsGPaWaS7zuHRnF7TAP+c9ku8C82+0wbsMIdqQLUrd6ITeSh1KFwNvBM2ghwdGVK0VG0RsD3aBYzMaFlE7C5a7a/FJRGrVAGcLNWtZbbXtiRWjOKiQghB1R+Aa+GWVuyCEXQdB04t89/1O/w1cDnyilFU='
  channel-secret: 'cad4cc2f471f47e7033193d13e919f72'
  handler.path: /callback
  
#logging.level:
#   com.linecorp.bot.client.wire: INFO