runtime: java
env: flex

handlers:
- url: /.*
  script: this field is required, but ignored

line.bot:
  channel-token: 'XVU8vgs/HMPqmDGiEPxiL0wwzaTs7oEczqQwo+S8/srdghtgWhPEZlUeAE3FEZsqSh1KFwNvBM2ghwdGVK0VG0RsD3aBYzMaFlE7C5a7a/Fbj1kKmbdKnmOinNTwKt339xDQQjYgBbSAwoMBvK7F7AdB04t89/1O/w1cDnyilFU='
  channel-secret: '27a1dd973d0db2e97fc3811a248ed91a'
  handler.path: /webhook
